apiVersion: apps/v1
kind: Deployment
metadata:
  name: besu
  namespace: besu-interbank
  labels: { app: besu }
spec:
  replicas: 1
  selector: { matchLabels: { app: besu } }
  template:
    metadata:
      labels: { app: besu }
    spec:
      containers:
        - name: besu
          image: hyperledger/besu:latest
          args:
            - --genesis-file=/genesis/genesis.json
            - --node-private-key-file=/secret/key
            - --data-path=/data
            - --min-gas-price=0
            - --rpc-http-enabled=true
            - --rpc-http-host=0.0.0.0
            - --rpc-http-port=8545
            - --rpc-http-cors-origins=*
            - --rpc-http-api=ETH,NET,WEB3,QBFT,ADMIN,TXPOOL,DEBUG
            - --host-allowlist=*
          ports:
            - { name: rpc, containerPort: 8545 }
          readinessProbe:
            tcpSocket: { port: 8545 }
            initialDelaySeconds: 4
            periodSeconds: 3
          livenessProbe:
            tcpSocket: { port: 8545 }
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - { name: genesis, mountPath: /genesis, readOnly: true }
            - { name: nodekey, mountPath: /secret, readOnly: true }
            - { name: data, mountPath: /data }
      volumes:
        - name: genesis
          configMap: { name: besu-genesis }
        - name: nodekey
          secret: { secretName: besu-node-key }
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: besu
  namespace: besu-interbank
spec:
  selector: { app: besu }
  ports:
    - { name: rpc, port: 8545, targetPort: 8545 }
